Repository SuteraVR/SuteraVR, pull requests merged in 2023-12, with the labels that each got.

#30 Create Rust project for suteravr-server
  server/Cargo.toml
  server/src/main.rs
Labels: ✨Feature, 🛠️Refactor

#32 Rewrite server/.gitignore and moved .gitignore to client/.gitignore
  client/.gitignore
  server/.gitignore
  server/.gitkeep
Labels: 🛠️Refactor

#54 feat(lib): created suteravr-lib
  .github/workflows/suteravr-lib-checker.yml
  suteravr-lib/.gitignore
  suteravr-lib/Cargo.toml
  suteravr-lib/src/lib.rs
Labels: ✨Feature
